### ISSUE TITLE
Errors with current test suite

### ISSUE THREAD

**Issue by jlepis** [benaston/NState#6]
First off - this is awesome. It looks really good. 

When I go to build the tests, I get a lot of errors. It looks like the tests have not been updated with some of your recent changes to the code base. Is this the case? Or am i doing something wrong?

The error that is most common is: 
Using the generic type 'NState.StateTransition<TState,TTransitionStatus>' requires 2 type arguments <Path>\NState-master\src\NState.Test.Fast\BugTrackerExample\BugTransition.cs

**Comment by benaston** [comment]
Thanks for the compliment.

I made a refactoring/improvement recently that I wanted to make available
to the public before I had time to update the test suite (bad practise I
know!).

Fixing the test suite shouldn't be too hard (I think I added an additional
type parameter somewhere, causing the error you are seeing). Contributions
welcome.

Thanks
Ben

**Comment by benaston** [comment]
Tests have now been fixed.

**Comment by jlepis** [comment]
Thanks man. You beat me to it! I grabbed latest, and it works like a charm.
